profile: full
ceip_policy_disclosed: true # Installation fails if this is set to 'false'
buildservice:
  kp_default_repository: "demo.goharbor.io/ktap/build-service"
  kp_default_repository_username: "kmantha"
  kp_default_repository_password: "Harbor123!"
  tanzunet_username: "abc"
  tanzunet_password: "def!"
  descriptor_name: "full"
  enable_automatic_dependency_updates: true
supply_chain: basic
#supply_chain: testing_scanning
cnrs:
  domain_name: cnr.tap.kamymantha.ninja
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  #default_tls_secret: tls-certs/tap-alexbrash-dev-wildcard
ootb_supply_chain_basic:
#ootb_supply_chain_testing_scanning:
  registry:
    server: "demo.goharbor.io" # TBS will write container images to this OCI registry 
    repository: "ktap"  # contairezed app images will go into this repo 
  gitops:
    ssh_secret: ""
# learning center
learningcenter:
  ingressDomain: "tlc.tap.kamymantha.ninja"
# tap gui
tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "tap.kamymantha.ninja"
  app_config:
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: "d3d7b5370b53a40b523e"  # you need to get this value from GitHub Developer Settings OAuth2 page
            clientSecret: "f24280e0f50454f48b13fbfd0a47153212dbc642"
    app:
      baseUrl: http://tap-gui.tap.kamymantha.ninja
    catalog:
      locations:
        - type: url
          target: https://github.com/KamyMantha/tap-gui-sample-catalog/blob/main/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.tap.kamymantha.ninja
      cors:
        origin: http://tap-gui.tap.kamymantha.ninja
# tap_gui:
#   service_type: ClusterIP
#   ingressEnabled: "true"
#   ingressDomain: "tap.alexanderbrash.dev"
#   tls:
#     secretName: tap-alexbrash-dev-wildcard
#     namespace: tls-certs
#   app_config:
#     auth:
#       allowGuestAccess: false
#       environment: development
#       providers:
#         microsoft:
#           development:
#             clientId: $CLIENT_ID
#             clientSecret: $CLIENT_SECRET
#             tenantId: $TENANT_ID
#     app:
#       baseUrl: https://tap-gui.tap.alexanderbrash.dev
#     catalog:
#       locations:
#         - type: url
#           target: https://github.com/badraoul/tap-test/blob/main/blank/catalog-info.yaml
#     backend:
#       baseUrl: https://tap-gui.tap.alexanderbrash.dev
#       cors:
#         origin: https://tap-gui.tap.alexanderbrash.dev
metadata_store:
  app_service_type: LoadBalancer # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
grype:
  #namespace: "dev" # (optional) Defaults to default namespace.
  targetImagePullSecret: "Harbor123!"
contour:
  envoy:
    service:
      type: LoadBalancer