profile: full  
ceip_policy_disclosed: true # Installation fails if this not set to `true`
buildservice:
  #asia.gcr.io/api-gw-on-gcp/build-service"
  kp_default_repository: "gcr.io/api-gw-on-gcp/build-service"
  kp_default_repository_username: _json_key
  kp_default_repository_password: |-
      {
        "type": "service_account",
        "project_id": "api-gw-on-gcp",
        "private_key_id": "eed7f930efc9baee46f6c1960246d17409abd1db",
        "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCryxr0hR1cRLEK\nhaLeoUk1z1gTUEIXDxSZ9pfLsBef41ZeNbccwBdSOv5U1ZSpmYaICoLD6k9wRABI\nfZSSkV/k7F3VDLpJqsrjL1MXElixB+DsLHCLcVMQ7MKrAh7CInXvVJcR4m/CVAUy\nleonxZWXdM10sHUI6Gs+oHu1FMJDCazgSJy/lKrMxcQzptPYvtAiWIbS+mZNqj/z\n4tdlegtxpyMVsb6ae3/NeDa8IHD3RtBiRBEEQdaGX3ITv9pk70ZzcubTL29EXJLD\nLJbDF1TlJZ8Y1PVblG+q7dgDJOrR5Mo4u3hDafyKryCudPopISgswDo7f6H05zzb\ngnebIA17AgMBAAECggEAI7uFukl7z2bMSkt8koEKqMIdaDr/3Cr7VoDnlurkJxIS\ns1rJ4RWFZEm3/+5C0zoHNQG2rEhuyIOkaW+ReSD6yLNvWvKgRtVbCQEdb8WVpBDm\n9EjUCfUC2ZjdbtNskWW4kRTPrV0jcNCoGhr7jtU2pb+aQoS3eyhYsjiQMpyEQYwI\ni+7z9q+PhrOu11SgKe4+my/bO3wt+vpW+nDzNtQy/Et4m14sasB82wQ/xTwHiQp5\nsV1lIJjdkM+zgDAg3VOauT9g/3nEx/hoO/wUVIxXUgEaPWYAbwolYESpsmmWBffJ\n/zUmF3OaOLj6ZdrYbMnN2Npa3YWMYCZ5EhTecRcBSQKBgQDljl00UoIb8JLOGfQn\nmskEGZ3cTwkm4uONEkVuKI3jNQk8ELSx50eq3NX6JQ/+2TmL0Ie0sKSNvaZ4g7+t\nIuBeBn+OdV9B4V1zZO364ZBSDYtPNrJvlQhr0QjSv1XaeAyQAsGVnwvFZ7IrG/QP\nIsjIZeeU6RUWrUESP9DEiWUhEwKBgQC/lU/MavDEz2y6V5HCy7kSMpTHZIZopUxR\nyuuqIIwoOj3wNLjYNhKqC9p6PGEVCGhbIvD7gZ3AMY6cUly5Ss0JN+K6yTOo4TRI\n8vxk3MqmXOLYZ55ofymb+JSYgiAEMwLUns2zHgfjxBknvKQzU00tvmkFx0ubG5NA\nNEYNSg/W+QKBgFDygL9gkOzVSo9O65/DnzrI5be4TxvdSiyG0uDjgBUssJLzuSQ6\n0DTaJsJMq3VMmFRLNm9rErvAsqEwpDijYccGN5i+ntaWZ+O3JYwgWkn06LkIKqfa\nP9v1HE1klxuw1Y06y5S9PuNfi55T/x4PQAoalS0XfA5BDf8nbbDAWl7tAoGBALS3\np7pv9gXwk+OCzyAtA7rCs80Saic0JbXR8FNeuFcJ+XsogGSTPS/iVoiPhBRPBgFS\nCHd2YNP260tR9d1jTd2wNdN0D6LyLFvTuXl7PD2JyQHRXH+91AYoiiMCPCk55SWj\nVu3rGg4j4Ia3TzyLC3Zm8rJcuFjrvg8GQD4w6pghAoGACFMgR5Qxv5T9RDHVuEQ6\nPfxd0Zu7flmbi5/CsDN0YTpgt+veDMf788x6/Z5vcia+f7Hz/NQNCeirbCL9neNL\nO3GsPiNWlYpsCrLVWNeLRbyxdH/e2Pfoz3d6cVYWvWcGNxMTSa0hC6Zssz4CwUQB\n+ugwFJco6Q30fhJQmYhRo84=\n-----END PRIVATE KEY-----\n",
        "client_email": "sa-tap@api-gw-on-gcp.iam.gserviceaccount.com",
        "client_id": "111521963393781462800",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sa-tap%40api-gw-on-gcp.iam.gserviceaccount.com"
      } 
  tanzunet_username: "kmantha@vmware.com"
  tanzunet_password: "VMware123!"
  descriptor_name: "full"
  enable_automatic_dependency_updates: true
cnrs:
  domain_name: cnr.tap.kamymantha.ninja
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  #default_tls_secret: tls-certs/tap-alexbrash-dev-wildcard
supply_chain: testing_scanning
ootb_supply_chain_testing_scanning:
  registry:
    server: "gcr.io"
    #server: "asia.gcr.io" # TBS will write container images to this OCI registry 
    repository: "api-gw-on-gcp/supply-chain"  # contairezed app images will go into this repo 
  # gitops:
  # server_address: https://github.com/
  # repository_owner: xxx
  # repository_name: xxx
  # ssh_secret: git-https
  # commit_strategy: pull_request
  # pull_request:
  #   server_kind: github
  #   pull_request_title: "Approval for Production deployment"
  #   pull_request_body: "Please review the configuration and approve the deployment"
  #   commit_branch: ""  
  gitops:
    #server_address: https://github.com/
    #repository: ssh://git@github.com/KamyMantha/
    #repository_owner: KamyMantha
    #repository_prefix: ssh://git@github.com/KamyMantha/devops-
    #repository_prefix: ssh://git@github.com/KamyMantha/
    repository_prefix: https://github.com/KamyMantha/devops-
    # branch: main
    # user_name: kamymantha
    # user_email: kamy_mantha@yahoo.com
    # commit_message: supplychain
    ssh_secret: git-ssh
  #git_implementation: libgit2
# learning center
learningcenter:
  ingressDomain: "tlc.tap.kamymantha.ninja"
# tap gui
tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "tap.kamymantha.ninja"
  app_config:
    app:
      baseUrl: http://tap-gui.tap.kamymantha.ninja
    catalog:
      locations:
        - type: url
          target: https://github.com/KamyMantha/tap-gui-sample-catalog/blob/main/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.tap.kamymantha.ninja
      cors:
        origin: http://tap-gui.tap.kamymantha.ninja

metadata_store:
  app_service_type: ClusterIP
  ingress_enabled: "true"
  ingress_domain: tap.kamymantha.ninja
grype:
  namespace: "dev3" # (optional) Defaults to default namespace.
  targetImagePullSecret: "registry-credentials"
contour:
  envoy:
    service:
      type: LoadBalancer
